version: "3.7"
services:
  dd-agent:
    image: datadog/agent:latest
    container_name: agent
    ports:
      - 127.0.0.1:8126:8126/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    deploy:
      restart_policy:
        condition: any
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
  dd-python-stack:
    build:
      context: ./python/
      dockerfile: Dockerfile
    environment:
      - DD_SERVICE="dd-python-stack"
      - SERVER_PORT=5000
    ports:
      - 127.0.0.1:5000:5000/tcp
  dd-golang-stack:
    build:
      context: ./golang/
      dockerfile: Dockerfile
    environment:
      - DD_SERVICE="dd-golang-stack"
      - SERVER_PORT=5001
    ports:
      - 127.0.0.1:5001:5001/tcp
  dd-java-stack:
    build:
      context: ./java/
      dockerfile: Dockerfile
    environment:
      - DD_SERVICE="dd-java-stack"
      - SERVER_PORT=5002
    ports:
      - 127.0.0.1:5002:5002/tcp